---
# run the playbook: 'ansible-playbook Libpam.yml -vvv'  
# run the playbook at the same level than ansible.cfg
# MIT License: https://mit-license.org/
# Add the PAM (Pluggable Authentication Modules) to the system
- hosts: all
#  vars_files:
#    - vars.yml
  tasks:
    - name: Install libpam-pwquality package
      apt:
        name: libpam-pwquality
        state: present
      become: yes
    - name: Install libpam-shield package
      apt:
        name: libpam-shield
        state: present
      become: yes
    - name: Install libpam-cracklib package
      apt:
        name: libpam-cracklib
        state: present
      become: yes
    - name: Install libpam-tmpdir package
      apt:
        name: libpam-tmpdir
        state: present
      become: yes