---
# run the playbook: 'ansible-playbook Bash_aliases.yml -vvv'  
# run the playbook at the same level than ansible.cfg
# MIT License: https://mit-license.org/
- name: Install and configure net-tools
  hosts: all
  become: yes
  tasks:
    - name: Install net-tools
      apt:
        name: net-tools
        state: present
        
    - name: Verify net-tools installation
      command: apt search net-tools
      changed_when: false
      
    - name: Print net-tools search results
      debug:
        var: net_tools_search.stdout_lines
        
    - name: Check open ports
      command: netstat -tap | grep LISTEN
      register: open_ports
      changed_when: false
      
    - name: Print open ports
      debug:
        var: open_ports.stdout_lines